[package]
name = "nes_sdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nes = { version = "0.1.0", path = "../nes" }
sdl2 = "0.35.2"

[profile.release]
lto = true
debug = true
