[package]
name = "nes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
png = "0.17"

[dependencies]
mos_6502 = { version = "0.1.0", path = "../mos_6502" }
